### ISSUE TITLE
Another library django-jsonfield already exists... and is in Debian/Ubuntu

### ISSUE THREAD

**Issue by robvdl** [dmkoch/django-jsonfield#120]
This really confused me for a while, your library is called "jsonfield" on pypi, not "django-jsonfield" which is on Bitbucket and also in the Ubuntu repository as the "python-django-jsonfield" package.

Not sure what can be done about this, but it's going to be confusing for a lot of people if they see this package in Debian, they think it's this library on Github... but it's not, it's the one on Bitbucket instead.

Even the import is the same "import jsonfield", meaning both packages can't be installed at the same time.

https://bitbucket.org/schinckel/django-jsonfield/

**Comment by bradjasper** [comment]
Unfortunately there is a name conflict & someone else has the other names. At this point merging projects might be best but I haven't discussed this with any other maintainers. I'd be open to it though.

**Comment by dmkoch** [comment]
Added some clarification in the README.

**Comment by sebhaase** [comment]
Please clearify this sentence:

This one is django-jsonfield here on GitHub but jsonfield on PyPI. 

should be rather:
This one is django-jsonfield here on GitHub - but jsonfield on PyPI is from Matthew Schinckel hosted at bitbucket.

**Comment by dmkoch** [comment]
My statement about this in the README is correct.  "jsonfield" on PyPI is this project, not Matthew Schinckel's.

**Comment by sebhaase** [comment]
Trying to rephrase my comment:

"  This one is django-jsonfield here on GitHub but jsonfield on PyPI
<https://pypi.python.org/pypi/jsonfield>.  "

is not proper English.  Why do you use "but" ?

Regards,
Sebastian

**Comment by dmkoch** [comment]
I'll clarify that sentence, thanks.
