### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by bradjasper** [dmkoch/django-jsonfield#146]
django-jsonfield is looking for someone to take over or help out with the maintenance of the project. I'm not able to commit as much time as I have in the past and don't want to see the project suffer.

There are a few open issues that need to be handled and a few pull request that could be merged in. I'm happy to help walk through some of these issues if anyone is interested.

**Comment by dmkoch** [comment]
I'm going to try to follow in @bradjasper's foot steps! Thanks for everything Brad.
