### ISSUE TITLE
Question:  Is the conversion from string to Python-dict cached ?

### ISSUE THREAD

**Issue by sebhaase** [dmkoch/django-jsonfield#186]
Maybe it could be documented, if (and maybe how) the expensive (?) conversion from the string (read from the db) is repeated for every access of this field, or if the resulting dict is cached.
Also, how is this cached dict being invalidated when the underlying string in the db changes ?

Thanks, S.

**Comment by dmkoch** [comment]
The module uses Python's standard json.loads() function to decode the JSON string. I believe on most platforms that will use fast C code to do the decoding. 

There is no explicit caching of the resulting dict -- you could certainly do that in your application code, but I wouldn't sweat it too much unless you profiled your code and saw a bottleneck with the json decode.
