### ISSUE TITLE
Publish 2.0.2 on pypi

### ISSUE THREAD

**Issue by nemesisdesign** [dmkoch/django-jsonfield#194]
I went crazy tracking down a bug that was solved in this commit: https://github.com/dmkoch/django-jsonfield/commit/a9190f6320ee03a330c0dd392c8112f220217bf0

Can someone issue a new release on pypi?

**Comment by jleclanche** [comment]
@dmkoch What's the status on 2.0.2?

**Comment by dmkoch** [comment]
Just published on PyPI.

**Comment by jleclanche** [comment]
Thanks!

**Comment by nemesisdesign** [comment]
Thanks
