### ISSUE TITLE
Import error on Django master (3.0) due to django.utils.six

### ISSUE THREAD

**Issue by therefromhere** [dmkoch/django-jsonfield#225]
django.utils.six has been removed on Django master, so this fails unless `six` is installed

```
try:
    from django.utils import six
except ImportError:
    import six
```

**Comment by therefromhere** [comment]
I think the short-term fix is to add six as a dependency, medium term is dropping py2 support so we don't need six.

**Comment by therefromhere** [comment]
Ah this is less pressing than I thought - Django master is now for django 3.0 release, not 2.2.

**Comment by therefromhere** [comment]
Looks like this project is abandoned, we've migrated to https://github.com/rpkilby/jsonfield2 instead.

**Comment by kstopa** [comment]
I've already created a pull request solving this issue

**Comment by dmkoch** [comment]
I release version 2.1.0 that should address
